db_of_em = open('db_of_em.txt', 'a')

c_name = input("company name:-")
e_name = input("employee name:-")
e_id = input("employee id:-")
mo = int(input("mobile no.:-"))
add = input("Address:-")
pos = input("position:-")
salary = int(input("salary:-"))
ta = salary * 0.02
da = salary * 0.05
hra = salary * 0.2
pf = salary * 0.15
total_salary = salary + ta + da + hra - pf

db_of_em.write('\ninformation'.center(50))
db_of_em.write(F'\ncompany name:-{c_name}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\nemployee name:-{e_name},         employee id:-{e_id}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\nmobile no.:-{mo},      position:-{pos}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\nAddress.:-{add}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\nsalary:-{salary}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\n+TA:-{ta}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\n+DA:-{da}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\n+HRA:-{hra}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\n-PF:-{pf}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write(F'\ntotal income:-{total_salary}')
db_of_em.write('\n-----------------------------------------------')
db_of_em.write('\n')
db_of_em.write('\n')
# print(db_of_em.readlines())
db_of_em.close()
print('\nInformation stored successfully')


# print('|company name:-', A, '                       |')
# print('|-----------------------------------------------|')
# print('|employee name:-', B, ',', 'employee id:-', C, '|')
# print('|-----------------------------------------------|')
# print('|mobile no.:-', D, ',   ', 'position:-', F, '|')
# print('|-----------------------------------------------|')
# print('|Address.:-', E, '                    |')
# print('|-----------------------------------------------|')
# print('|', 'salary:-                              ', G, '|')
# print('|-----------------------------------------------|')
# print('|', '+TA:-                                 ', I, '|')
# print('|-----------------------------------------------|')
# print('|', '+DA:-                                 ', J, '|')
# print('|-----------------------------------------------|')
# print('|', '+HRA:-                               ', K, '|')
# print('|-----------------------------------------------|')
# print('|', '-PF:-                                ', L, '|')
# print('|-----------------------------------------------|')
# print('|', 'total income:-                      ', M, '|')
# print('|-----------------------------------------------|')
