db_of_sm = open('db_of_sm.txt', 'a')

A = input("student name:-")
B = input("semester:-")
C = input("stream:-")
D = input("roll no.:-")
E = input("enrollment no.:-")
F = input("college name:-")
print('---:Enter Marks For Given Subjects:---')
G = int(input("Maths:-"))
H = int(input("Physics:-"))
I = int(input("Chemistry:-"))
J = "------"
K = (G+H+I)/3

db_of_sm.write(F'\n{J}result{J}')
db_of_sm.write(F'\n{J+F+J}')
db_of_sm.write(F'\n{J+A+J}')
db_of_sm.write(F'\n{B}  {C}  {D}')
db_of_sm.write(F'\n{E}')
db_of_sm.write(F'\nMaths\t\t\t{G}')
db_of_sm.write(F'\nPhysics\t\t\t{H}')
db_of_sm.write(F'\nChemistry\t\t{I}')
db_of_sm.write(F'\n{J+J+J}')
db_of_sm.write(F'\nTotal Marks\t\t{K}%')
db_of_sm.write('\n\n')
db_of_sm.close()
print('\nInformation stored successfully')


# print(J+F+J)
# print(J+A+J)
# print(B, '', C, '', D)
# print(E)
# print('Maths\t\t\t', G)
# print('Physics\t\t\t', H)
# print('Chemistry\t\t', I)
# print(J+J+J)
# print('Total Marks\t\t', K, '%')
